apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mynodeapp
spec:
  replicas: 5
  selector:
    matchLabels:
      app: mynodeapp
  template:
    metadata:
      labels:
        app: mynodeapp
    spec:
      containers:
      - name: mynodeapp
        image: mycontainerregistrymp111.azurecr.io/mynodeapp:1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 8888
---
apiVersion: v1
kind: Service
metadata:
  name: nodeappsrv
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: mynodeapp